export { Hero } from "./Hero";
export { Problem } from "./Problem";
export { Solution } from "./Solution";
export { HowItWorks } from "./HowItWorks";
export { Features } from "./Features";
export { Testimonials } from "./Testimonials";
export { FAQ } from "./FAQ";
export { CTA } from "./CTA";
export { Footer } from "./Footer";
